### ISSUE TITLE
TLS and Basic Auth Config Flag not working

### ISSUE THREAD

**Issue by Eforen** [prometheus/exporter-toolkit#42]
Not sure if I am stupid or the documentation is incomplete or something.

I am unable to get the webconfig file working

```
>"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter  --telemetry.addr :9182 --web.config.file C:\Monitoring\web.yaml
windows_exporter.exe: error: unknown long flag '--web.config.file', try --help
```

my web.yaml is 
```yaml
tls_server_config:
  cert_file: C:\Monitoring\cert.crt
  key_file: C:\Monitoring\cert.key

basic_auth_users:
  prometheus: [redacted]
```
